gh-16 Add support for Wildfly Maven plugin
* Works with Wildfly 8.1 and 9.0.0.Alpha1.
* Removed Client JSF state saving section, which causes deployment
exception "Unable to find the encoded key.:
javax.naming.NameNotFoundException: env/jsf/ClientSideSecretKey".